### PR TITLE
[splash screen] move dependency checking to a class of its own and install each dependency if it's not installed.

### PR DESCRIPTION
**Pull request by Itai-Nelken**
UNTESTED!

### CODE REVIEW

**Comment by Itai-Nelken** [comment]
Tested but not inside PiGro

**Comment by Itai-Nelken** [comment]
the `popen('pip3 install distro')` is breaking for some reason.

**Comment by Itai-Nelken** [comment]
I fixed all problems.
now the dependencies are checked in a different thread, and the splash screen is only destroyed once the function that checks the dependencies finishes.

**Comment by actionschnitzel** [comment]
Wow thanks a lot! Code looks nice. My code was just quick solution after I realised at 3.A.M. that something is not working :-)

**Comment by Itai-Nelken** [comment]
TBH I barely know python...

**Pull request merged**
